spring:
  application:
    name: greeting-service

greeting-service:
    greeting: "Olá"
    default-value: "Mundo Prod"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'